# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
