# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_auto_20160502_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appoint',
            name='phone',
        ),
        migrations.AddField(
            model_name='appoint',
            name='contact',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
