# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_auto_20160502_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='time',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
