# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160428_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_text',
            new_name='name',
        ),
    ]
