# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0002_auto_20160502_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 22, 3, 31, 241255)),
        ),
    ]
