# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector', '0006_auto_20160523_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 20, 11, 57, 352950)),
        ),
    ]
