# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime(2016, 5, 2, 10, 29, 25, 645008))),
                ('verify', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
