# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 22, 3, 31, 243560)),
        ),
    ]
